version: '3.8'
services:
  service:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres:14.4-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
